# -*- coding: utf-8 -*-
"""Team Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTQnWxrzK7ZZBP-6Q34ZcCd0KhGHsurr

<h1>Bank Customer Churn Prediction Team Project</h1>
<h2>Group Members</h2>
<ul>
  <li><strong>Tomas King | ID: 000819529 | Email: tking109@students.kennesaw.edu</strong></li>
  <li><strong>Casey Gilliam | ID: 000860691| Email: cgilli10@students.kennesaw.edu</strong></li>
  <li><strong>Rohini Paithanker | ID: 000980941 | Email: rpaithan@students.kennesaw.edu</strong></li>
  <li><strong>Gowtamy Reddy Godhala | ID: 001108343 | Email: ggodhala@students.kennesaw.edu</strong></li>
</ul>
"""

# Google Collab was used to coordinate the notebook accross the team
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

path = "/content/drive/MyDrive/CSV/churn.csv"
df = pd.read_csv(path)

"""<h1>Preliminary Analysis</h1>"""

df.info()

df

"""<h2>Histograms & Value Counts for Preliminary Analysis</h2>"""

df.hist(bins = 5)

df.hist(bins=50, figsize=(25,10), grid=False) #bins
plt.show()

df["Gender"].value_counts().plot.bar(y='count', rot=0)

df["Geography"].value_counts().plot.bar(y='count', rot=0)

print(df['Geography'].value_counts())

df['CreditScore'].hist(bins=200, figsize=(25,5), grid=False) #bins
plt.show()

df['CreditScore'].value_counts()

df['Age'].hist(bins=75, figsize=(25,5), grid=False) #bins
plt.show()

df['Tenure'].hist(bins=22, figsize=(10,5), grid=False) #bins
plt.show()

df['Balance'].hist(bins=50, figsize=(20,5), grid=False) #bins
plt.show()

df['Balance'].value_counts()

df['NumOfProducts'].hist(bins=30, figsize=(10,5), grid=False) #bins
plt.show()

df['NumOfProducts'].value_counts()

df["HasCrCard"].value_counts().plot.bar(y='count', rot=0)

df['HasCrCard'].value_counts()

df["IsActiveMember"].value_counts().plot.bar(y='count', rot=0)

df['IsActiveMember'].value_counts()

df['EstimatedSalary'].hist(bins=50, figsize=(10,5), grid=False) #bins
plt.show()

df["Exited"].value_counts().plot.bar(y='count', rot=0)

df['Exited'].value_counts()

"""<h1>Preprocessing</h1>"""

# Dropping the 'RowNumber', 'CustomerId', 'Surname', and 'Geography' columns
df_dropped= df.drop(['RowNumber', 'CustomerId', 'Surname', 'Geography'], axis=1)

print(df_dropped.head())

# Apply one-hot encoding to the 'Gender' column
df_prepro= pd.get_dummies(df_dropped, columns=['Gender'])

# Reorder the columns to make 'Exited' the last column
column_order = [col for col in df_prepro.columns if col != 'Exited'] + ['Exited']
df_fp = df_prepro[column_order]

print(df_fp.head())

#Hypothesis 1 dropping the values to make a data frame to run without them to see impact on model
df_ph1 = df_fp.drop(['Age', 'Tenure'], axis=1)
#Hypothesis 2 dropping values for hypothesis 2 data frame
df_ph2 = df_fp.drop(['NumOfProducts', 'HasCrCard', 'IsActiveMember'], axis=1)

"""<h3>Train Test Split & Pipeline</h3>"""

#Split the data set with the whole dataset to be used on a base line to compare hypothesis models
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer


x = df_fp.drop('Exited', axis=1)
y = df_fp['Exited']

trainX, testX, trainY, testY = train_test_split(x, y, test_size=0.2)

num_cols = trainX.columns[(trainX.dtypes == np.int64) | (trainX.dtypes == np.float64)]
#Standardization and yeo-johnson transformation used to account for some outliers and skewing in the data
num_pipeline = Pipeline([
    ('scaler', PowerTransformer(method='yeo-johnson'))
])

full_pipeline = ColumnTransformer([
    ('numeric', num_pipeline, num_cols),
])
#Apply the pipeline TrainX_prc is the base line train and test data set
trainX_prc = full_pipeline.fit_transform(trainX)
testX_prc = full_pipeline.transform(testX)
trainX_prc.shape, testX_prc.shape

#Split the data from hypothesis 1 dataframe
x_h1 = df_ph1.drop('Exited', axis=1)
y_h1 = df_ph1['Exited']

trainX_h1, testX_h1, trainY_h1, testY_h1 = train_test_split(x_h1, y_h1, test_size=0.2)

num_cols_h1 = trainX_h1.columns[(trainX_h1.dtypes == np.int64) | (trainX_h1.dtypes == np.float64)]
#Apply the pipeline to the split dataset
num_pipeline_h1 = Pipeline([
    ('scaler', PowerTransformer(method='yeo-johnson'))
])

full_pipeline_h1 = ColumnTransformer([
    ('numeric', num_pipeline_h1, num_cols_h1),
])

trainX_prc_h1 = full_pipeline_h1.fit_transform(trainX_h1)
testX_prc_h1 = full_pipeline_h1.transform(testX_h1)
trainX_prc_h1.shape, testX_prc_h1.shape
#trainX_prc_h1 and testX_prc_h1 are to be used for H1 testing models

#Split the data from hypotheis 2 dataframe
x_h2 = df_ph2.drop('Exited', axis=1)
y_h2 = df_ph2['Exited']

trainX_h2, testX_h2, trainY_h2, testY_h2 = train_test_split(x_h2, y_h2, test_size=0.2)

num_cols_h2 = trainX_h2.columns[(trainX_h2.dtypes == np.int64) | (trainX_h2.dtypes == np.float64)]
#Apply the pipeline to hypothesis 2 dataframe
num_pipeline_h2 = Pipeline([
    ('scaler', PowerTransformer(method='yeo-johnson'))
])

full_pipeline_h2 = ColumnTransformer([
    ('numeric', num_pipeline_h2, num_cols_h2),
])

trainX_prc_h2 = full_pipeline_h2.fit_transform(trainX_h2)
testX_prc_h2 = full_pipeline_h2.transform(testX_h2)
trainX_prc_h2.shape, testX_prc_h2.shape
#trainX_prc_h2 and testX_prc_h2 are to be used for H2 testing models

"""<h1>Model Selection, Training & Fine-tuning</h1>

<h1>Random Forest</h1>

<h2>Base Model</h2>
<p>Split Values: (trainX_prc, trainY), (testX_prc, testY) </p>
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV

# Initialize the Random Forest Classifier with a range of depths to try
rf = RandomForestClassifier(random_state=42)

# Setup the parameters and distributions to use
param_dist = {'max_depth': [3, 5, 10, 20, 40, None]}

# Instantiate the GridSearchCV object: rf_cv
rf_cv = GridSearchCV(rf, param_dist, scoring='accuracy', cv=5)

# Fit it to the training data
rf_cv.fit(trainX_prc, trainY)

# Print the tuned parameters and score
print("Tuned Random Forest Parameters: {}".format(rf_cv.best_params_))
print("Best score is {}".format(rf_cv.best_score_))

# Predict on the test set
test_pred = rf_cv.predict(testX_prc)

# Evaluate the model
accuracy = accuracy_score(testY, test_pred)
precision = precision_score(testY, test_pred)
recall = recall_score(testY, test_pred)
f1 = f1_score(testY, test_pred)

# Print the evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

"""<h2>Hypothesis 1</h2>
<p>Split Values: (trainX_prc_h1, trainY_h1), (testX_prc_h1, testY_h1) </p>
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV

# Initialize the Random Forest Classifier
rf_h1 = RandomForestClassifier(random_state=42)

# Define a range of "max_depth" values to explore which depth is best
param_grid_h1 = {
    'max_depth': [3, 5, 10, 20, None],
}

# Setup GridSearchCV to find the best 'max_depth' using cross-validation
grid_search_h1 = GridSearchCV(estimator=rf_h1, param_grid=param_grid_h1, cv=5, scoring='accuracy', n_jobs=-1)

# Fit the grid search to the data
grid_search_h1.fit(trainX_prc_h1, trainY_h1)

# Retrieve the best hyperparameters
best_params_h1 = grid_search_h1.best_params_
best_depth_h1 = best_params_h1['max_depth']
print(f"Best parameters for Hypothesis 1: {best_params_h1}")

# Use the best model to predict on the test set
best_rf_h1 = grid_search_h1.best_estimator_
test_pred_h1 = best_rf_h1.predict(testX_prc_h1)

# Calculate evaluation metrics
accuracy_h1 = accuracy_score(testY_h1, test_pred_h1)
precision_h1 = precision_score(testY_h1, test_pred_h1)
recall_h1 = recall_score(testY_h1, test_pred_h1)
f1_h1 = f1_score(testY_h1, test_pred_h1)

# Print the evaluation metrics
print(f"Accuracy for Hypothesis 1: {accuracy_h1:.2f}")
print(f"Precision for Hypothesis 1: {precision_h1:.2f}")
print(f"Recall for Hypothesis 1: {recall_h1:.2f}")
print(f"F1 Score for Hypothesis 1: {f1_h1:.2f}")

# Print the best depth
print(f"Best depth for Hypothesis 1: {best_depth_h1}")

"""<h2>Hypothesis 2</h2>
<p>Split Values: (trainX_prc_h2, trainY_h2), (testX_prc_h2, testY_h2) </p>
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV

# Initialize the Random Forest Classifier for Hypothesis 2
rf_h2 = RandomForestClassifier(random_state=42)

# Define a range of "max_depth" values for Hypothesis 2
param_grid_h2 = {
    'max_depth': [3, 5, 10, 20, None],
}

# Setup GridSearchCV for Hypothesis 2
grid_search_h2 = GridSearchCV(estimator=rf_h2, param_grid=param_grid_h2, cv=5, scoring='accuracy', n_jobs=-1)

# Fit the grid search to the data for Hypothesis 2
grid_search_h2.fit(trainX_prc_h2, trainY_h2)

# Retrieve the best hyperparameters for Hypothesis 2
best_params_h2 = grid_search_h2.best_params_
best_depth_h2 = best_params_h2['max_depth']
print(f"Best parameters for Hypothesis 2: {best_params_h2}")

# Use the best model from grid search to predict on the test set for Hypothesis 2
best_rf_h2 = grid_search_h2.best_estimator_
test_pred_h2 = best_rf_h2.predict(testX_prc_h2)

# Calculate evaluation metrics for Hypothesis 2
accuracy_h2 = accuracy_score(testY_h2, test_pred_h2)
precision_h2 = precision_score(testY_h2, test_pred_h2)
recall_h2 = recall_score(testY_h2, test_pred_h2)
f1_h2 = f1_score(testY_h2, test_pred_h2)

# Print the evaluation metrics for Hypothesis 2
print(f"Accuracy for Hypothesis 2: {accuracy_h2:.2f}")
print(f"Precision for Hypothesis 2: {precision_h2:.2f}")
print(f"Recall for Hypothesis 2: {recall_h2:.2f}")
print(f"F1 Score for Hypothesis 2: {f1_h2:.2f}")

# Print the best depth for Hypothesis 2
print(f"Best depth for Hypothesis 2: {best_depth_h2}")

"""```
# This is formatted as code
```

<h1>L1 Regularization</h1>

<h2>Base Model</h2>
<p>Split Values: (trainX_prc, trainY), (testX_prc, testY) </p>
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Assuming you have preprocessed data stored in trainX_prc, testX_prc, trainY, and testY

# Create a Logistic Regression model with L1 regularization
logistic_l1 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=3000)

# Define the parameter grid for hyperparameter tuning
param_grid = [{'C': [0.001, 0.01, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000]}]


# Initialize GridSearchCV
logistic_l1_cv = GridSearchCV(logistic_l1, param_grid, scoring='accuracy', cv=5)

# Fit the model
logistic_l1_cv.fit(trainX_prc, trainY)

# Print the tuned parameters and score
print("Tuned Logistic Regression (L1) Parameters: {}".format(logistic_l1_cv.best_params_))
print("Best score is {}".format(logistic_l1_cv.best_score_))

# Optionally, predict on the test set and evaluate the performance
test_pred_logistic_l1 = logistic_l1_cv.predict(testX_prc)
accuracy_logistic_l1 = accuracy_score(testY, test_pred_logistic_l1)
print("Accuracy on the test set: {}".format(accuracy_logistic_l1))

# Get the best L1 logistic regression model
best_l1_logistic = logistic_l1_cv.best_estimator_

# Predict on the test set
test_pred_logistic_l1 = best_l1_logistic.predict(testX_prc)

# Evaluate the model
accuracy_logistic_l1 = accuracy_score(testY, test_pred_logistic_l1)
precision_logistic_l1 = precision_score(testY, test_pred_logistic_l1)
recall_logistic_l1 = recall_score(testY, test_pred_logistic_l1)
f1_logistic_l1 = f1_score(testY, test_pred_logistic_l1)

# Print the evaluation metrics for L1 regularization
print("\nL1 Regularization Evaluation Metrics:")
print(f"Accuracy: {accuracy_logistic_l1:.2f}")
print(f"Precision: {precision_logistic_l1:.2f}")
print(f"Recall: {recall_logistic_l1:.2f}")
print(f"F1 Score: {f1_logistic_l1:.2f}")

"""<h2>Hypothesis 1</h2>
<p>Split Values: (trainX_prc_h1, trainY_h1), (testX_prc_h1, testY_h1) </p>
"""

# Perform a grid search for L1 regularization
logistic_l1 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=3000)
param_grid_h1_l1 = [{'C': [0.001, 0.01, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000]}]

grid_search_h1_l1 = GridSearchCV(logistic_l1, param_grid_h1_l1, cv=5, scoring='accuracy', return_train_score=True)
grid_search_h1_l1.fit(trainX_prc_h1, trainY_h1)

# Get the best estimator from the grid search
best_l1_logistic_h1 = grid_search_h1_l1.best_estimator_

# Predict on the test set for Hypothesis 1 with L1 regularization
test_pred_logistic_h1 = best_l1_logistic_h1.predict(testX_prc_h1)

# Evaluate the model for Hypothesis 1 with L1 regularization
accuracy_l1_h1 = accuracy_score(testY_h1, test_pred_logistic_h1)
precision_l1_h1 = precision_score(testY_h1, test_pred_logistic_h1)
f1_l1_h1 = f1_score(testY_h1, test_pred_logistic_h1)
recall_l1_h1 = recall_score(testY_h1, test_pred_logistic_h1)


# Print the evaluation metrics for Hypothesis 1 with L1 regularization
print(f"Accuracy for Hypothesis 1 with L1 regularization: {accuracy_l1_h1:.2f}")
print(f"Precision for Hypothesis 1 with L1 regularization: {precision_l1_h1:.2f}")
print(f"F1 Score for Hypothesis 1 with L1 regularization: {f1_l1_h1:.2f}")
print(f"Recall for Hypothesis 1 with L1 regularization: {recall_l1_h1:.2f}")

"""<h2>Hypothesis 2</h2>
<p>Split Values: (trainX_prc_h2, trainY_h2), (testX_prc_h2, testY_h2) </p>
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Creating model
logistic_l1_h2 = LogisticRegression(penalty='l1', solver='liblinear', max_iter=3000)

# Defining the parameter grid for hyperparameter tuning
param_grid_l1_h2 = [{'C': [0.05, 0.1, 0.5, 1, 5, 10, 50, 100]}]

# Applying L1 regularization using GridSearchCV
grid_search_l1_h2 = GridSearchCV(logistic_l1_h2, param_grid_l1_h2, cv=5, scoring='accuracy', return_train_score=True)
grid_search_l1_h2.fit(trainX_prc_h2, trainY_h2)

# Get best param and accuracy for train model with L1 regularization
print(grid_search_l1_h2.best_params_)
print(grid_search_l1_h2.best_score_) # accuracy

# Obtaining metrics for test model after tuning with L1 regularization
best_l1_logistic_h2 = grid_search_l1_h2.best_estimator_
accuracy_l1_h2 = best_l1_logistic_h2.score(testX_prc_h2, testY_h2)
f1_l1_h2 = f1_score(testY_h2, best_l1_logistic_h2.predict(testX_prc_h2))
precision_l1_h2 = precision_score(testY_h2, best_l1_logistic_h2.predict(testX_prc_h2))
recall_l1_h2 = recall_score(testY_h2, best_l1_logistic_h2.predict(testX_prc_h2))

# Print the evaluation metrics for hypothesis 2 with L1 regularization
print(f"Accuracy for hypothesis 2 (L1): {accuracy_l1_h2:.2f}")
print(f"Precision for hypothesis 2 (L1): {precision_l1_h2:.2f}")
print(f"F1 Score for hypothesis 2 (L1): {f1_l1_h2:.2f}")
print(f"Recall for hypothesis 2 (L1): {recall_l1_h2:.2f}")

"""<h1>L2 Regularization</h1>

<h2>Base Model</h2>
<p>Split Values: (trainX_prc, trainY), (testX_prc, testY) </p>
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_score, recall_score

#creating model
logistic = LogisticRegression()

from sklearn.model_selection import GridSearchCV
param_grid = [{'C': [ 0.05, 0.1, 0.5, 1 , 5, 10, 50, 100]}]

#L2 regularization is used for fine tuning
logistic = LogisticRegression(penalty='l2', max_iter=3000)
grid_search = GridSearchCV(logistic, param_grid, cv=5, scoring='accuracy', return_train_score=True)
grid_search.fit(trainX_prc,trainY)

# Get best param and accuracy for train model
print(grid_search.best_params_)
print(grid_search.best_score_) #accuracy

# Obtaining metrics for test model after tuning
best_l2_logistic = grid_search.best_estimator_
accuracy = best_l2_logistic.score(testX_prc, testY)
f1 = f1_score(testY, best_l2_logistic.predict(testX_prc))
precision = precision_score(testY, best_l2_logistic.predict(testX_prc))
recall = recall_score(testY, best_l2_logistic.predict(testX_prc))

# Print the evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"F1 Score: {f1:.2f}")
print(f"Recall: {recall:.2f}")

"""<h2>Hypothesis 1</h2>
<p>Split Values: (trainX_prc_h1, trainY_h1), (testX_prc_h1, testY_h1) </p>
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_score, recall_score

#creating model
logistic = LogisticRegression()

from sklearn.model_selection import GridSearchCV
param_grid_h1 = [{'C': [ 0.05, 0.1, 0.5, 1 , 5, 10, 50, 100]}]

#L2 regularization is used for fine tuning
logistic = LogisticRegression(penalty='l2', max_iter=3000)
grid_search_h1 = GridSearchCV(logistic, param_grid_h1, cv=5, scoring='accuracy', return_train_score=True)
grid_search_h1.fit(trainX_prc_h1,trainY_h1)

# Get best param and accuracy for train model
print(grid_search_h1.best_params_)
print(grid_search_h1.best_score_) #accuracy

# Obtaining metrics for test model after tuning
best_l2_logistic = grid_search_h1.best_estimator_
accuracy_h1 = best_l2_logistic.score(testX_prc_h1, testY_h1)
f1_h1 = f1_score(testY_h1, best_l2_logistic.predict(testX_prc_h1))
precision_h1 = precision_score(testY_h1, best_l2_logistic.predict(testX_prc_h1))
recall_h1 = recall_score(testY_h1, best_l2_logistic.predict(testX_prc_h1))

# Print the evaluation metrics
print(f"Accuracy for hypothesis1: {accuracy_h1:.2f}")
print(f"Precision for hypothesis1: {precision_h1:.2f}")
print(f"F1 Score for hypothesis1: {f1_h1:.2f}")
print(f"Recall for hypothesis1: {recall_h1:.2f}")

"""<h2>Hypothesis 2</h2>
<p>Split Values: (trainX_prc_h2, trainY_h2), (testX_prc_h2, testY_h2) </p>
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, precision_score, recall_score

#creating model
logistic = LogisticRegression()

from sklearn.model_selection import GridSearchCV
param_grid_h2 = [{'C': [ 0.05, 0.1, 0.5, 1 , 5, 10, 50, 100]}]

#L2 regularization is used for fine tuning
logistic = LogisticRegression(penalty='l2', max_iter=3000)
grid_search_h2 = GridSearchCV(logistic, param_grid_h2, cv=5, scoring='accuracy', return_train_score=True)
grid_search_h2.fit(trainX_prc_h2,trainY_h2)

# Get best param and accuracy for train model
print(grid_search_h2.best_params_)
print(grid_search_h2.best_score_) #accuracy

# Obtaining metrics for test model after tuning
best_l2_logistic = grid_search_h2.best_estimator_
accuracy_h2 = best_l2_logistic.score(testX_prc_h2, testY_h2)
f1_h2 = f1_score(testY_h2, best_l2_logistic.predict(testX_prc_h2))
precision_h2 = precision_score(testY_h2, best_l2_logistic.predict(testX_prc_h2))
recall_h2 = recall_score(testY_h2, best_l2_logistic.predict(testX_prc_h2))

# Print the evaluation metrics for hypothesis 2
print(f"Accuracy for hypothesis 2: {accuracy_h2:.2f}")
print(f"Precision for hypothesis 2: {precision_h2:.2f}")
print(f"F1 Score for hypothesis 2: {f1_h2:.2f}")
print(f"Recall for hypothesis 2: {recall_h2:.2f}")

"""<h1>Neural Network</h1>

<h2>Base Model</h2>
<p>Split Values: (trainX_prc, trainY), (testX_prc, testY) </p>
"""

#Untuned Neural Network results for comparison using the base model
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import precision_score

n_features = trainX_prc.shape[1] #get the number of input features
mlp = MLPClassifier(hidden_layer_sizes=[n_features,n_features,n_features], max_iter=1000)

mlp.fit(trainX_prc, trainY)
print('Train Score Untuned:', mlp.score(trainX_prc, trainY))
print('Test Score Untuned:', mlp.score(testX_prc, testY))
# Get Precision score for untuned model
predictions = mlp.predict(testX_prc)
precision = precision_score(testY, predictions)
print('Precision Untuned:',precision)

#Finetune the model using hpyerparameters
from sklearn.model_selection import GridSearchCV

param_grid = [{
    'hidden_layer_sizes' : [[n_features,n_features],                       #two hidden layer with n_features neurons
                            [n_features,n_features,n_features],            #three hidden layer with n_features neurons
                            [n_features//2,n_features//2],                 #two hidden layer with n_features/2 neurons
                            [n_features//2,n_features//2,n_features//2],   #three hidden layer with n_features/2 neurons
                            [n_features*2,n_features*2],                   #two hidden layer with n_features*2 neurons
                            [n_features*2,n_features*2,n_features*2]],     #three hidden layer with n_features*2 neurons
    'alpha' : [0.001, 0.01, 0.1, 1, 10]                                    #regularization terms
}]

mlp = MLPClassifier(max_iter=1000)

grid_search = GridSearchCV(mlp, param_grid, cv=3, scoring='accuracy', return_train_score=True)

grid_search.fit(trainX_prc,trainY)

#Best parameters for NN
print(grid_search.best_params_)
print(grid_search.best_score_)

#Scores for finetuned models
best_nn = grid_search.best_estimator_
print('Test Accuracy Tuned:',best_nn.score(testX_prc, testY))
#test prediction
BasePredNN = best_nn.predict(testX_prc)
#test precision
BaseNNpre = precision_score(testY, BasePredNN)
#test recall
BaseNNrec = recall_score(testY, BasePredNN)
#test f1 score
BaseNNf1 = f1_score(testY, BasePredNN)
print('Precision Score:', BaseNNpre)
print('Recall Score:', BaseNNrec)
print('F1 Score:', BaseNNf1)

#Train Score to check for overfitting
best_nn.score(trainX_prc, trainY)

"""<h2>Hypothesis 1</h2>
<p>Split Values: (trainX_prc_h1, trainY_h1), (testX_prc_h1, testY_h1) </p>
"""

#Untuned Neural Network results for comparison using the Hypotheis 1 model
from sklearn.neural_network import MLPClassifier

n_features = trainX_prc_h1.shape[1] #get the number of input features
mlp = MLPClassifier(hidden_layer_sizes=[n_features,n_features,n_features], max_iter=1000)

mlp.fit(trainX_prc_h1, trainY_h1)
print('Train Score h1 untuned:',mlp.score(trainX_prc_h1, trainY_h1))
print('Test Score h1 untuned:',mlp.score(testX_prc_h1, testY_h1))
# Get untuned precision score
predictions = mlp.predict(testX_prc_h1)
precision = precision_score(testY_h1, predictions)
print('Precision untuned:',precision)

#Finetune the model using hpyerparameters
from sklearn.model_selection import GridSearchCV

param_grid = [{
    'hidden_layer_sizes' : [[n_features,n_features],                       #two hidden layer with n_features neurons
                            [n_features,n_features,n_features],            #three hidden layer with n_features neurons
                            [n_features//2,n_features//2],                 #two hidden layer with n_features/2 neurons
                            [n_features//2,n_features//2,n_features//2],   #three hidden layer with n_features/2 neurons
                            [n_features*2,n_features*2],                   #two hidden layer with n_features*2 neurons
                            [n_features*2,n_features*2,n_features*2]],     #three hidden layer with n_features*2 neurons
    'alpha' : [0.001, 0.01, 0.1, 1, 10]                                    #regularization terms
}]

mlp = MLPClassifier(max_iter=1000)

grid_search = GridSearchCV(mlp, param_grid, cv=3, scoring='accuracy', return_train_score=True)

grid_search.fit(trainX_prc_h1,trainY_h1)

#Best parameters for NN
print(grid_search.best_params_)
print(grid_search.best_score_)

#Scores for finetuned models
best_nn = grid_search.best_estimator_
print('Test Accuracy Tuned H1:',best_nn.score(testX_prc_h1, testY_h1))
h1PredNN = best_nn.predict(testX_prc_h1)
#test precision
h1NNpre = precision_score(testY_h1, BasePredNN)
#test recall
h1NNrec = recall_score(testY_h1, BasePredNN)
#test f1 score
h1NNf1 = f1_score(testY_h1, h1PredNN)
print('Precision Score:', h1NNpre)
print('Recall Score:', h1NNrec)
print('F1 Score:', h1NNf1)

#Train Score to check for overfitting
best_nn.score(trainX_prc_h1, trainY_h1)

"""<h2>Hypothesis 2</h2>
<p>Split Values: (trainX_prc_h2, trainY_h2), (testX_prc_h2, testY_h2) </p>
"""

#Untuned Neural Network results for comparison using the Hypotheis 2 model
from sklearn.neural_network import MLPClassifier

n_features = trainX_prc_h2.shape[1] #get the number of input features
mlp = MLPClassifier(hidden_layer_sizes=[n_features,n_features,n_features], max_iter=1000)

mlp.fit(trainX_prc_h2, trainY_h2)
print('Train Score Untuned:',mlp.score(trainX_prc_h2, trainY_h2))
print('Test Score untuned:', mlp.score(testX_prc_h2, testY_h2))
# Get untuned test precision score
predictions = mlp.predict(testX_prc_h2)
precision = precision_score(testY_h2, predictions)
print('Precision Test untuned:',precision)

#Finetune the model using hpyerparameters
from sklearn.model_selection import GridSearchCV

param_grid = [{
    'hidden_layer_sizes' : [[n_features,n_features],                       #two hidden layer with n_features neurons
                            [n_features,n_features,n_features],            #three hidden layer with n_features neurons
                            [n_features//2,n_features//2],                 #two hidden layer with n_features/2 neurons
                            [n_features//2,n_features//2,n_features//2],   #three hidden layer with n_features/2 neurons
                            [n_features*2,n_features*2],                   #two hidden layer with n_features*2 neurons
                            [n_features*2,n_features*2,n_features*2]],     #three hidden layer with n_features*2 neurons
    'alpha' : [0.001, 0.01, 0.1, 1, 10]                                    #regularization terms
}]

mlp = MLPClassifier(max_iter=1000)

grid_search = GridSearchCV(mlp, param_grid, cv=3, scoring='accuracy', return_train_score=True)

grid_search.fit(trainX_prc_h2,trainY_h2)

#Best parameters for NN
print(grid_search.best_params_)
print(grid_search.best_score_)

#Scores for finetuned models
best_nn = grid_search.best_estimator_
print('Test Accuracy Tuned H1:',best_nn.score(testX_prc_h2, testY_h2))
h2PredNN = best_nn.predict(testX_prc_h2)
#test precision
h2NNpre = precision_score(testY_h2, h2PredNN)
#test recall
h2NNrec = recall_score(testY_h2, h2PredNN)
#test f1 score
h2NNf1 = f1_score(testY_h2, h2PredNN)
print('Precision Score:', h2NNpre)
print('Recall Score:', h2NNrec)
print('F1 Score:', h2NNf1)

#Train Score to check for overfitting
best_nn.score(trainX_prc_h2, trainY_h2)

"""<h1>Tuned Model Scores/Conclusion</h1>

<h2>Base Model</h2>

| Base Model Scores | Random Forest | l1 Regularization | l2 Regularization | Neural Network |
|----------|------------|------------|----------|----------|
|Accuracy  | 0.86 | 0.82 | 0.82 | 0.86|
|Precision | 0.76 | 0.57 | 0.58 | 0.74|
|Recall    | 0.43 | 0.22 | 0.22 | 0.44|
|F1 Score  | 0.55 | 0.32 | 0.31 | 0.55|

<h2>Hypothesis 1 Model</h2>

| Hypothesis 1 Model Scores | Random Forest | l1 Regularization | l2 Regularization | Neural Network |
|----------|------------|------------|----------|----------|
|Accuracy  | 0.82 | 0.79 | 0.79 | 0.81|
|Precision | 0.88 | 0.0  | 0.0  | 0.18|
|Recall    | 0.14 | 0.0  | 0.0  | 0.10|
|F1 Score  | 0.24 | 0.0  | 0.0  | 0.23|

<h2>Hypothesis 2 Model</h2>

| Hypothesis 2 Model Scores | Random Forest | l1 Regularization | l2 Regularization | Neural Network |
|----------|------------|------------|----------|----------|
|Accuracy  | 0.80 | 0.77 | 0.77 | 0.81|
|Precision | 0.65 | 0.39 | 0.40 | 0.67|
|Recall    | 0.23 | 0.07 | 0.07 | 0.29|
|F1 Score  | 0.34 | 0.12 | 0.12 | 0.40|

"""

